"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  Archive, ArrowRight, BarChart3, Bot, Box, Boxes, Camera, Check, ChevronDown,
  ChevronRight, CircleHelp, ExternalLink, Eye, Filter, FolderPlus, FolderTree,
  Grid2X2, ImagePlus, Images, LayoutDashboard, List, MapPin, Menu,
  MoreHorizontal, PackagePlus, Paperclip, Plus, Search, Settings, Sparkles,
  Tag, X
} from "lucide-react";

export type Item = {
  id:number; serial:string; title:string; category:string; source:string; location:string;
  location_id?:number|null; quantity:number; status:string; image:string; description:string;
  tags:string[]; confidence?:number; imageCount?:number; price_text?:string;
};

type Location = {id:number;name:string;parent_id:number|null;notes?:string};

const INVENTORY_SCROLL_KEY="parts-atlas-inventory-scroll";
const INVENTORY_QUERY_KEY="parts-atlas-inventory-query";
const INVENTORY_SCROLL_TTL=5*60*1000;

async function webReadyImage(file:File){if(file.size<800*1024)return file;const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")?.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.8));bitmap.close();return blob?new File([blob],`${file.name.replace(/\.[^.]+$/,"")}.webp`,{type:"image/webp"}):file}

export default function Home(){
  const[items,setItems]=useState<Item[]>([]);
  const[query,setQuery]=useState("");
  const[activeNav,setActiveNav]=useState("Overview");
  const[view,setView]=useState<"grid"|"list">("grid");
  const[selected,setSelected]=useState<Item|null>(null);
  const[modal,setModal]=useState<"camera"|"ai"|null>(null);
  const[selectedSources,setSelectedSources]=useState<string[]>([]);
  const[selectedCategories,setSelectedCategories]=useState<string[]>([]);
  const[selectedTags,setSelectedTags]=useState<string[]>([]);
  const[filterPreferencesReady,setFilterPreferencesReady]=useState(false);
  const[toast,setToast]=useState("");
  const[loading,setLoading]=useState(true);
  const pendingInventoryScroll=useRef<number|null>(null);
  const restoringInventoryScroll=useRef(false);
  const restoringInventoryQuery=useRef(false);

  const refresh=()=>fetch("/api/items?limit=1000").then(r=>r.json()).then(d=>{setItems(d.items||[]);setLoading(false)}).catch(()=>setLoading(false));
  useEffect(()=>{if("scrollRestoration" in history)history.scrollRestoration="manual";refresh();const params=new URLSearchParams(window.location.search);const requested=params.get("view");if(requested&&["Overview","Inventory","Locations","Settings","Help & feedback"].includes(requested))setActiveNav(requested);if(requested==="Inventory"){try{const saved=JSON.parse(sessionStorage.getItem(INVENTORY_SCROLL_KEY)||"null");if(saved&&Number.isFinite(saved.y)&&Number.isFinite(saved.savedAt)&&Date.now()-saved.savedAt<=INVENTORY_SCROLL_TTL)pendingInventoryScroll.current=Math.max(0,saved.y);else sessionStorage.removeItem(INVENTORY_SCROLL_KEY)}catch{sessionStorage.removeItem(INVENTORY_SCROLL_KEY)}try{const saved=JSON.parse(sessionStorage.getItem(INVENTORY_QUERY_KEY)||"null");if(saved&&typeof saved.query==="string"&&Number.isFinite(saved.savedAt)&&Date.now()-saved.savedAt<=INVENTORY_SCROLL_TTL){restoringInventoryQuery.current=true;setQuery(saved.query)}else sessionStorage.removeItem(INVENTORY_QUERY_KEY)}catch{sessionStorage.removeItem(INVENTORY_QUERY_KEY)}}if(params.get("modal")==="ai")setModal("ai")},[]);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("parts-atlas-inventory-filters")||"{}");if(Array.isArray(saved.categories))setSelectedCategories(saved.categories);if(Array.isArray(saved.tags))setSelectedTags(saved.tags)}catch{}finally{setFilterPreferencesReady(true)}},[]);
  useEffect(()=>{if(filterPreferencesReady)localStorage.setItem("parts-atlas-inventory-filters",JSON.stringify({categories:selectedCategories,tags:selectedTags}))},[filterPreferencesReady,selectedCategories,selectedTags]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(timer)},[toast]);
  useEffect(()=>{if(activeNav!=="Inventory")return;if(restoringInventoryQuery.current){restoringInventoryQuery.current=false;return}if(query)sessionStorage.setItem(INVENTORY_QUERY_KEY,JSON.stringify({query,savedAt:Date.now()}));else sessionStorage.removeItem(INVENTORY_QUERY_KEY)},[activeNav,query]);
  useEffect(()=>{if(activeNav!=="Inventory")return;const onScroll=()=>{if(restoringInventoryScroll.current)return;sessionStorage.setItem(INVENTORY_SCROLL_KEY,JSON.stringify({y:window.scrollY,savedAt:Date.now()}))};window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[activeNav]);
  useEffect(()=>{if(activeNav!=="Inventory"||loading||!filterPreferencesReady||pendingInventoryScroll.current===null)return;const target=pendingInventoryScroll.current;pendingInventoryScroll.current=null;restoringInventoryScroll.current=true;let frame=0;let request=0;const restore=()=>{window.scrollTo({top:target,left:0,behavior:"auto"});if(frame++<3)request=requestAnimationFrame(restore);else restoringInventoryScroll.current=false};request=requestAnimationFrame(restore);return()=>{cancelAnimationFrame(request);restoringInventoryScroll.current=false}},[activeNav,loading,filterPreferencesReady]);

  const categories=useMemo(()=>[...new Set(items.map(i=>i.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[items]);
  const categoryCounts=useMemo(()=>{const counts=new Map<string,number>();items.forEach(i=>counts.set(i.category,(counts.get(i.category)||0)+1));return [...counts].sort((a,b)=>a[0].localeCompare(b[0]))},[items]);
  const tagCounts=useMemo(()=>{const counts=new Map<string,number>();items.forEach(i=>i.tags.forEach(t=>counts.set(t,(counts.get(t)||0)+1)));return [...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))},[items]);
  const sources=useMemo(()=>[...new Set(items.map(i=>i.source))].sort(),[items]);
  const sourceCounts=useMemo(()=>sources.map(source=>[source,items.filter(item=>item.source===source).length] as [string,number]),[items,sources]);
  const filtered=useMemo(()=>items.filter(item=>{
    const text=`${item.title} ${item.serial} ${item.category} ${item.tags.join(" ")}`.toLowerCase();
    return text.includes(query.toLowerCase())
      &&(!selectedSources.length||selectedSources.includes(item.source))
      &&(!selectedCategories.length||selectedCategories.includes(item.category))
      &&(!selectedTags.length||selectedTags.some(tag=>item.tags.includes(tag)));
  }),[items,query,selectedSources,selectedCategories,selectedTags]);
  const totalUnits=items.reduce((sum,item)=>sum+item.quantity,0);

  const toggle=(value:string,list:string[],set:(next:string[])=>void)=>set(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
  const clearFilters=()=>{setSelectedSources([]);setSelectedCategories([]);setSelectedTags([])};
  const navigateTo=(name:string)=>{setActiveNav(name);window.history.replaceState({},"",name==="Overview"?"/":`/?view=${encodeURIComponent(name)}`)};

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Boxes size={20}/></div><span>Parts<span>Atlas</span></span></div>
      <button className="mobile-menu" aria-label="Menu"><Menu/></button>
      <nav><p>Workspace</p>{[
        {n:"Overview",i:LayoutDashboard},{n:"Inventory",i:Archive},{n:"Locations",i:FolderTree}
      ].map(({n,i:Icon})=><button key={n} className={activeNav===n?"active":""} onClick={()=>navigateTo(n)}><Icon size={19}/>{n}{n==="Inventory"&&<span>{items.length}</span>}</button>)}
      <Link className="sidebar-link" href="/identify"><Camera size={19}/>Identify</Link>
      <p>Intelligence</p><Link className="sidebar-link" href="/assistant"><Sparkles size={19}/>Lab assistant<span className="beta">AI</span></Link>
      <p>System</p><button className={activeNav==="Settings"?"active":""} onClick={()=>navigateTo("Settings")}><Settings size={19}/>Settings</button><button className={activeNav==="Help & feedback"?"active":""} onClick={()=>navigateTo("Help & feedback")}><CircleHelp size={19}/>Help & feedback</button></nav>
      <div className="storage-card"><div><span>Managed storage</span><b>6,337 images</b></div><div className="meter"><i/></div><small>Product photos and attachments</small></div>
      <div className="profile"><div>RL</div><span><b>Roy&apos;s Lab</b><small>Personal workspace</small></span><MoreHorizontal size={18}/></div>
    </aside>

    <section className="content"><header className="topbar"><div className="crumb"><span>Home lab</span><ChevronRight size={15}/><b>{activeNav}</b></div><div className="top-actions"><Link className="identify-button top-link" href="/identify"><Camera size={18}/>Identify an item</Link><Link className="add-button top-link" href="/items/new"><Plus size={18}/>Add item</Link></div></header>
      <div className="page">
        {activeNav==="Overview"&&<OverviewView items={items} totalUnits={totalUnits} categories={categories} onInventory={()=>navigateTo("Inventory")} onAsk={()=>{window.location.href="/assistant"}} onItem={setSelected}/>} 
        {activeNav==="Inventory"&&<InventoryView loading={loading} items={filtered} total={items.length} query={query} setQuery={setQuery} view={view} setView={setView} sourceCounts={sourceCounts} categoryCounts={categoryCounts} tagCounts={tagCounts} selectedSources={selectedSources} selectedCategories={selectedCategories} selectedTags={selectedTags} toggleSource={v=>toggle(v,selectedSources,setSelectedSources)} toggleCategory={v=>toggle(v,selectedCategories,setSelectedCategories)} toggleTag={v=>toggle(v,selectedTags,setSelectedTags)} clearFilters={clearFilters} onItem={setSelected}/>} 
        {activeNav==="Locations"&&<LocationsView items={items}/>} 
        {activeNav==="Settings"&&<PendingView icon={<Settings/>} title="Settings" description="Workspace and inventory preferences will live here."/>}
        {activeNav==="Help & feedback"&&<PendingView icon={<CircleHelp/>} title="Help & feedback" description="Guides and feedback options will live here."/>}
      </div>
    </section>

    {selected&&<ItemPanel item={selected} onClose={()=>setSelected(null)} onAsk={()=>setModal("ai")} onUpdated={async()=>{await refresh();const updated=(await (await fetch(`/api/items?id=${selected.id}`)).json()).items?.[0];if(updated)setSelected(updated)}}/>}
    {modal==="ai"&&<AssistantModal onClose={()=>setModal(null)} item={selected}/>} 
    {toast&&<div className="toast"><Sparkles size={18}/>{toast}</div>}
  </main>
}

function OverviewView({items,totalUnits,categories,onInventory,onAsk,onItem}:{items:Item[];totalUnits:number;categories:string[];onInventory:()=>void;onAsk:()=>void;onItem:(item:Item)=>void}){
  const located=items.filter(i=>i.location&&i.location!=="Unsorted").length;
  const topCategories=useMemo(()=>{const counts=new Map<string,number>();items.forEach(i=>counts.set(i.category,(counts.get(i.category)||0)+1));return [...counts].sort((a,b)=>b[1]-a[1]).slice(0,6)},[items]);
  return <div className="overview"><div className="welcome"><div><p className="eyebrow">Your workshop at a glance</p><h1>Good morning, Roy.</h1><p>See what you own, what still needs a home, and where to start next.</p></div><button className="overview-inventory" onClick={onInventory}>Browse all inventory <ArrowRight/></button></div>
    <div className="stats"><Stat icon={<Boxes/>} tone="blue" label="Unique products" value={items.length.toLocaleString()} note={`${categories.length} categories`}/><Stat icon={<Box/>} tone="mint" label="Estimated units" value={totalUnits.toLocaleString()} note="Including multi-packs"/><Stat icon={<MapPin/>} tone="orange" label="Items located" value={located.toLocaleString()} note={`${items.length-located} still need a location`}/><Stat icon={<Images/>} tone="yellow" label="Product images" value={items.reduce((n,i)=>n+(i.imageCount||0),0).toLocaleString()} note="Stored and searchable"/></div>
    <div className="ai-strip"><div className="ai-orb"><Sparkles/></div><div><b>Your lab has possibilities.</b><span>Ask for a project using parts you already own.</span></div><button onClick={onAsk}>Ask lab assistant <ChevronRight/></button></div>
    <div className="overview-grid"><section className="overview-card"><div className="overview-card-head"><div><BarChart3/><span><b>Largest categories</b><small>Where most of your inventory lives</small></span></div></div><div className="category-bars">{topCategories.map(([name,count])=><div key={name}><span>{name}</span><div><i style={{width:`${Math.max(8,count/(topCategories[0]?.[1]||1)*100)}%`}}/></div><b>{count}</b></div>)}</div></section><section className="overview-card"><div className="overview-card-head"><div><Archive/><span><b>Recently imported</b><small>Latest products in your catalog</small></span></div><button onClick={onInventory}>View all</button></div><div className="recent-list">{items.slice(0,5).map(item=><button key={item.id} onClick={()=>onItem(item)}><div className="recent-thumb">{item.image?<img src={item.image} alt=""/>:<ImagePlus/>}</div><span><b>{item.title}</b><small>{item.category} · {item.source}</small></span><ChevronRight/></button>)}</div></section></div>
  </div>
}

function InventoryView({loading,items,total,query,setQuery,view,setView,sourceCounts,categoryCounts,tagCounts,selectedSources,selectedCategories,selectedTags,toggleSource,toggleCategory,toggleTag,clearFilters,onItem}:{loading:boolean;items:Item[];total:number;query:string;setQuery:(v:string)=>void;view:"grid"|"list";setView:(v:"grid"|"list")=>void;sourceCounts:[string,number][];categoryCounts:[string,number][];tagCounts:[string,number][];selectedSources:string[];selectedCategories:string[];selectedTags:string[];toggleSource:(v:string)=>void;toggleCategory:(v:string)=>void;toggleTag:(v:string)=>void;clearFilters:()=>void;onItem:(item:Item)=>void}){
  const activeCount=selectedSources.length+selectedCategories.length+selectedTags.length;
  return <div className="inventory-page"><div className="inventory-title"><div><p className="eyebrow">Everything you own</p><h1>Inventory</h1><p>{items.length.toLocaleString()} of {total.toLocaleString()} products shown</p></div><div className="quick-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names, serial numbers, categories, or tags…"/></div></div>
    <div className="filter-workbench"><div className="filter-top"><div><Filter/><b>Refine inventory</b>{activeCount>0&&<span>{activeCount} selected</span>}</div>{activeCount>0&&<button onClick={clearFilters}>Clear all</button>}</div><div className="facet-grid"><Facet title="Source" values={sourceCounts} selected={selectedSources} onToggle={toggleSource}/><Facet title="Categories" values={categoryCounts} selected={selectedCategories} onToggle={toggleCategory} searchable/><Facet title="Tags" values={tagCounts} selected={selectedTags} onToggle={toggleTag} searchable/></div></div>
    <div className="section-head inventory-results"><div><h2>Products</h2><span>{items.length.toLocaleString()} results</span></div><div className="view-toggle"><button className={view==="grid"?"on":""} onClick={()=>setView("grid")} aria-label="Grid view"><Grid2X2/></button><button className={view==="list"?"on":""} onClick={()=>setView("list")} aria-label="List view"><List/></button></div></div>
    {loading?<div className="empty"><Boxes/><h3>Loading your inventory…</h3></div>:items.length?<div className={`inventory ${view}`}>{items.map(item=>view==="list"?<ListItemRow key={item.id} item={item} onOpen={()=>onItem(item)}/>:<ItemCard key={item.id} item={item} onOpen={()=>onItem(item)}/>)}</div>:<div className="empty"><Search/><h3>No matching products</h3><p>Clear a filter or try a broader search.</p></div>}
  </div>
}

function Facet({title,values,selected,onToggle,searchable=false}:{title:string;values:[string,number][];selected:string[];onToggle:(value:string)=>void;searchable?:boolean}){
  const[search,setSearch]=useState("");const shown=values.filter(([value])=>value.toLowerCase().includes(search.toLowerCase()));
  return <section className="facet"><div className="facet-title"><b>{title}</b><span>{selected.length?`${selected.length} selected`:`${values.length} available`}</span></div>{searchable&&<label className="facet-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={title==="Categories"?"Find a category…":"Find a tag…"}/></label>}<div className="facet-options">{shown.map(([value,count])=><label key={value} className={selected.includes(value)?"selected":""}><input type="checkbox" checked={selected.includes(value)} onChange={()=>onToggle(value)}/><i>{selected.includes(value)&&<Check/>}</i><span>{value}</span>{count>0&&<small>{count}</small>}</label>)}</div></section>
}

function ItemCard({item,onOpen}:{item:Item;onOpen:()=>void}){
  const summary=item.description?.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()||"No description available yet.";
  return <article className="item-card" onClick={onOpen} tabIndex={0} onKeyDown={event=>event.key==="Enter"&&event.target===event.currentTarget&&onOpen()}><div className="card-top"><div className="photo">{item.image?<img src={item.image} alt={item.title}/>:<div className="no-photo"><ImagePlus/><span>No image</span></div>}<span className={`source ${item.source.toLowerCase()}`}>{item.source}</span></div><div className="card-intro"><div className="serial">{item.serial}</div><h3>{item.title}</h3><p>{summary}</p></div><Link className="card-menu" href={`/items/${item.id}`} target="_blank" rel="noopener noreferrer" aria-label={`Open ${item.title} product page in a new tab`} title="Open product page in a new tab" onClick={event=>event.stopPropagation()}><ExternalLink/></Link></div><div className="item-body"><div className="card-category"><Tag/><span>{item.category}</span></div>{item.tags.length>0&&<div className="card-tags">{item.tags.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}{item.tags.length>3&&<span>+{item.tags.length-3}</span>}</div>}<div className="card-foot"><span><b>{item.quantity}</b> {item.quantity===1?"unit":"units"}</span><span className="card-location"><MapPin/>{item.location&&item.location!=="Unsorted"?item.location:"Location not assigned"}</span></div></div></article>
}

function ListItemRow({item,onOpen}:{item:Item;onOpen:()=>void}){
  const summary=item.description?.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()||"No description available yet.";
  return <article className="inventory-list-row" onClick={onOpen} tabIndex={0} onKeyDown={event=>event.key==="Enter"&&event.target===event.currentTarget&&onOpen()}>
    <div className="list-row-photo">{item.image?<img src={item.image} alt={item.title}/>:<ImagePlus/>}<span className={`source ${item.source.toLowerCase()}`}>{item.source}</span></div>
    <div className="list-row-copy"><div><span>{item.serial}</span><h3>{item.title}</h3></div><p>{summary}</p></div>
    <div className="list-row-classification"><b><Tag/>{item.category}</b>{item.tags.length>0&&<span>{item.tags.slice(0,3).join(" · ")}</span>}</div>
    <div className="list-row-stock"><span><b>{item.quantity}</b> {item.quantity===1?"unit":"units"}</span><span><MapPin/>{item.location&&item.location!=="Unsorted"?item.location:"Location not assigned"}</span></div>
    <Link className="list-row-open" href={`/items/${item.id}`} target="_blank" rel="noopener noreferrer" aria-label={`Open ${item.title} product page in a new tab`} title="Open product page in a new tab" onClick={event=>event.stopPropagation()}><ExternalLink/></Link>
  </article>
}

function Stat({icon,tone,label,value,note}:{icon:React.ReactNode;tone:string;label:string;value:string;note:string}){return <div className="stat"><div className={`stat-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}

function PendingView({icon,title,description}:{icon:React.ReactNode;title:string;description:string}){return <div className="empty">{icon}<h1>{title}</h1><p>{description}</p></div>}

function LocationsView({items}:{items:Item[]}){const[locations,setLocations]=useState<Location[]>([]);const[parent,setParent]=useState<number|null>(null);const[name,setName]=useState("");const load=()=>fetch("/api/locations").then(r=>r.json()).then(d=>setLocations(d.locations||[]));useEffect(()=>{load()},[]);async function create(){if(!name.trim())return;await fetch("/api/locations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,parentId:parent})});setName("");await load()}return <div className="locations-page"><div className="locations-title"><div><p className="eyebrow">A place for every part</p><h1>Location map</h1><p>Create shelves, boxes, drawers, and bags in one storage tree.</p></div></div><div className="locations-grid"><section className="tree-card"><div className="tree-head"><span><FolderTree/>Storage tree</span></div><LocationTree locations={locations} selected={parent} onSelect={setParent}/></section><section className="location-summary"><div className="summary-hero"><div><FolderPlus/></div><span>Create a location</span><h2>{parent?`Inside ${locations.find(l=>l.id===parent)?.name}`:"At the root"}</h2><p>Choose a parent on the left, then name the new folder.</p></div><div className="new-location-form"><label>Location name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Box 3"/></label><button onClick={create}><Plus/>Create location</button></div><div className="location-stats"><div><b>{locations.length}</b><span>Locations</span></div><div><b>{items.filter(i=>i.location!=="Unsorted").length}</b><span>Placed items</span></div><div><b>{items.filter(i=>i.location==="Unsorted").length}</b><span>Unplaced</span></div></div></section></div></div>}

function LocationTree({locations,selected,onSelect}:{locations:Location[];selected:number|null;onSelect:(id:number|null)=>void}){const render=(parent:number|null,depth=0):React.ReactNode=>locations.filter(l=>(l.parent_id??null)===parent).map(location=><div key={location.id}><button type="button" className={`tree-row ${selected===location.id?"chosen":""}`} style={{paddingLeft:14+depth*22}} onClick={()=>onSelect(location.id)}><span className="tree-chevron"><ChevronRight/></span><span className="tree-icon"><Archive/></span><b>{location.name}</b>{selected===location.id&&<Check/>}</button>{render(location.id,depth+1)}</div>);return <div className="tree"><button type="button" className={`tree-row ${selected===null?"chosen":""}`} onClick={()=>onSelect(null)}><span className="tree-icon"><FolderTree/></span><b>Home lab (root)</b>{selected===null&&<Check/>}</button>{render(null)}</div>}

function ItemPanel({item,onClose,onAsk,onUpdated}:{item:Item;onClose:()=>void;onAsk:()=>void;onUpdated:()=>void}){const[images,setImages]=useState<Array<{id:number;url:string;filename:string}>>([]);const[hero,setHero]=useState(item.image);const input=useRef<HTMLInputElement>(null);const load=()=>fetch(`/api/uploads?itemId=${item.id}`).then(r=>r.json()).then(d=>setImages(d.images||[]));useEffect(()=>{load()},[item.id]);async function upload(files:FileList|null){if(!files)return;for(let n=0;n<files.length;n++){const form=new FormData();form.append("itemId",String(item.id));form.append("order",String(images.length+n));form.append("file",await webReadyImage(files[n]));const result=await(await fetch("/api/uploads",{method:"POST",body:form})).json();if(!hero)setHero(result.url)}await load();onUpdated()}return <div className="overlay panel-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="detail-panel"><div className="panel-top"><span>Item details</span><div><Link href={`/items/${item.id}`} target="_blank" rel="noopener noreferrer"><ExternalLink/>Open product page</Link><button onClick={onClose}><X/></button></div></div><div className="detail-image">{hero?<img src={hero} alt={item.title}/>:<div className="no-photo"><ImagePlus/><span>No product image</span></div>}<span className="confidence"><Images/>{images.length||item.imageCount||0} images</span></div><div className="detail-content"><div className="gallery-head"><b>Product images</b><button onClick={()=>input.current?.click()}><ImagePlus/>Add images</button><input ref={input} hidden type="file" accept="image/*" multiple onChange={e=>upload(e.target.files)}/></div>{images.length>1&&<div className="image-gallery">{images.slice(0,8).map((image,index)=><button key={image.id} onClick={()=>setHero(image.url)}><img src={image.url} alt={`${item.title} ${index+1}`}/>{index===7&&images.length>8?<span>+{images.length-8}</span>:null}</button>)}</div>}<span className="serial">{item.serial}</span><h2>{item.title}</h2><p>{item.description}</p><div className="tag-row">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div><dl><div><dt>Category</dt><dd>{item.category}</dd></div><div><dt>Source</dt><dd>{item.source}</dd></div><div><dt>Quantity estimate</dt><dd>{item.quantity} units</dd></div><div><dt>Location</dt><dd><MapPin/>{item.location||"Not assigned"}</dd></div></dl><button className="assistant-action" onClick={onAsk}><Sparkles/><span><b>Ask about this item</b><small>Find specifications, wiring help, or project ideas</small></span><ChevronRight/></button><div className="attachments-head"><b>Attachments</b><button><Paperclip/>Add file</button></div><div className="attachment empty-attachment"><div><Paperclip/></div><span><b>No attachments yet</b><small>Add a datasheet, manual, or receipt</small></span></div></div></aside></div>}

function AddModal({categories,onClose,onSubmit}:{categories:string[];onClose:()=>void;onSubmit:(form:FormData)=>void|Promise<void>}){return <div className="overlay"><form className="modal add-modal" action={onSubmit}><div className="modal-head"><div><span className="modal-icon"><PackagePlus/></span><div><h2>Add an inventory item</h2><p>Use an existing category and location, or create a new one here.</p></div></div><button type="button" onClick={onClose}><X/></button></div><label className="upload-zone"><ImagePlus/><b>Add product photos</b><span>Choose one or several images</span><strong>Choose photos</strong><input name="photos" hidden type="file" accept="image/*" multiple/></label><div className="form-grid"><label className="wide">Item name<input name="title" required placeholder="e.g. ESP32 development board"/></label><label>Category<input name="category" list="existing-categories" required placeholder="Select or type a new category"/><datalist id="existing-categories">{categories.map(category=><option key={category} value={category}/>)}</datalist><small>Typing a new name creates a new category.</small></label><label>Quantity<input name="quantity" type="number" min="1" defaultValue="1"/></label><label className="wide">Tags<input name="tags" placeholder="sensor, i2c, 5v"/><small>Separate tags with commas.</small></label><div className="wide"><LocationPicker/></div><label className="wide">Notes<textarea name="description" placeholder="Markings, measurements, specifications, or other details…"/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary">Add item</button></div></form></div>}

function LocationPicker(){const[locations,setLocations]=useState<Location[]>([]);const[selected,setSelected]=useState<number|null>(null);const[creating,setCreating]=useState(false);const[newName,setNewName]=useState("");const load=()=>fetch("/api/locations").then(r=>r.json()).then(d=>setLocations(d.locations||[]));useEffect(()=>{load()},[]);async function create(){if(!newName.trim())return;const response=await fetch("/api/locations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newName,parentId:selected})});const data=await response.json();await load();setSelected(data.location.id);setNewName("");setCreating(false)}return <div className="location-picker"><div className="location-picker-head"><span><FolderTree/>Location</span><button type="button" onClick={()=>setCreating(!creating)}><FolderPlus/>New location</button></div><p>Select a folder just like choosing a destination in Windows.</p><input type="hidden" name="locationId" value={selected||""}/><div className="location-picker-tree"><LocationTree locations={locations} selected={selected} onSelect={setSelected}/></div>{creating&&<div className="inline-location"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder={selected?`New folder inside ${locations.find(l=>l.id===selected)?.name}`:"New root location"}/><button type="button" onClick={create}><Plus/>Create</button></div>}</div>}

function CameraModal({items,onClose,onSelect}:{items:Item[];onClose:()=>void;onSelect:(item:Item)=>void}){const video=useRef<HTMLVideoElement>(null);const[running,setRunning]=useState(false);const[scanned,setScanned]=useState(false);async function start(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});if(video.current){video.current.srcObject=stream;await video.current.play();setRunning(true)}}catch{setRunning(false)}}useEffect(()=>()=>{const stream=video.current?.srcObject as MediaStream|null;stream?.getTracks().forEach(track=>track.stop())},[]);return <div className="overlay"><div className="modal camera-modal"><div className="modal-head"><div><span className="modal-icon coral"><Camera/></span><div><h2>Identify an unknown item</h2><p>Hold one component steady inside the frame.</p></div></div><button onClick={onClose}><X/></button></div><div className="camera-view"><video ref={video} muted playsInline/><div className="scan-frame"><i/><i/><i/><i/></div>{!running&&<div className="camera-empty"><Camera/><b>Camera is ready when you are</b><span>You can also upload a clear photo.</span></div>}</div>{scanned?<div className="matches"><div><Sparkles/><span><b>Likely inventory matches</b><small>Compare the photos and choose one</small></span></div>{items.slice(0,3).map((item,index)=><button key={item.id} onClick={()=>onSelect(item)}><img src={item.image} alt=""/><span><b>{item.title}</b><small>{96-index*5}% visual match</small></span><ChevronRight/></button>)}</div>:<div className="camera-actions"><button className="primary" onClick={running?()=>setScanned(true):start}><Camera/>{running?"Find matches":"Use camera"}</button></div>}<p className="privacy">Images are not saved unless you choose to attach them.</p></div></div>}

function AssistantModal({onClose,item}:{onClose:()=>void;item:Item|null}){const[text,setText]=useState("");const[messages,setMessages]=useState<string[]>([]);function ask(question:string){setMessages([...messages,question]);setText("")}return <div className="overlay"><div className="modal assistant-modal"><div className="assistant-head"><div><span><Bot/></span><div><h2>Lab assistant</h2><p><i/>Ready · knows your inventory</p></div></div><button onClick={onClose}><X/></button></div><div className="chat-body"><div className="bot-message"><span><Sparkles/></span><div><b>What are we making today?</b><p>I can search your inventory, identify missing details, suggest compatible parts, and turn your components into a build plan.</p></div></div>{item&&<div className="context-pill">{item.image&&<img src={item.image} alt=""/>}<span>Currently viewing <b>{item.title}</b></span></div>}{messages.map((message,index)=><div className="conversation" key={index}><div className="user-message">{message}</div><div className="bot-reply"><Sparkles/><p>I found relevant parts in your inventory. I can turn this into a compatibility checklist and a step-by-step build plan.</p></div></div>)}{messages.length===0&&<div className="prompts"><p>Try asking</p>{["What can I build this weekend?","Which items still need a location?","Find parts compatible with my ESP32"].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ChevronRight/></button>)}</div>}</div><form className="chat-input" onSubmit={event=>{event.preventDefault();if(text.trim())ask(text)}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about your parts or a project…"/><button><ChevronRight/></button></form></div></div>}
